In [28]:
import numpy as np
import pandas as pd

In [29]:
soccer_df1 = pd.read_csv('C:/half-time-analyze/win-nonwin/res/soccer.csv', header = 0, engine = 'python')
soccer_df2 = pd.read_csv('C:/half-time-analyze/win-nonwin/res/soccer2.csv', header = 0, engine = 'python')
soccer_df3 = pd.read_csv('C:/half-time-analyze/win-nonwin/res/soccer3.csv', header = 0, engine = 'python')

In [30]:
soccer_df = pd.concat([soccer_df1, soccer_df2, soccer_df3])
soccer_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 536 entries, 0 to 171
Data columns (total 61 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Match_date                536 non-null    object 
 1   teamName                  536 non-null    object 
 2   homeAway                  536 non-null    int64  
 3   Ball Possession           530 non-null    float64
 4   Goal Attempts             530 non-null    float64
 5   Shots On                  530 non-null    float64
 6   Shots Off                 530 non-null    float64
 7   Blocked Shots             530 non-null    float64
 8   Free kick                 530 non-null    float64
 9   Offsides                  530 non-null    float64
 10  Throw Ins                 530 non-null    float64
 11  Saves                     530 non-null    float64
 12  Fouls Commited            530 non-null    float64
 13  Red Cards                 530 non-null    float64
 14  Yellow Car

In [31]:
soccer_half_df = soccer_df[['homeAway', 'Ball Possession 1st Half', 'Corners 1st Half', 'Fouls Commited 1st Half', 'Goals 1st Half', 'Red Cards 1st Half', 'Shots Off 1st Half','Shots On 1st Half', 'Yellow Cards 1st Half', 'Result']]
soccer_half_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 536 entries, 0 to 171
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   homeAway                  536 non-null    int64  
 1   Ball Possession 1st Half  530 non-null    float64
 2   Corners 1st Half          530 non-null    float64
 3   Fouls Commited 1st Half   530 non-null    float64
 4   Goals 1st Half            530 non-null    float64
 5   Red Cards 1st Half        530 non-null    float64
 6   Shots Off 1st Half        530 non-null    float64
 7   Shots On 1st Half         530 non-null    float64
 8   Yellow Cards 1st Half     530 non-null    float64
 9   Result                    530 non-null    object 
dtypes: float64(8), int64(1), object(1)
memory usage: 46.1+ KB


In [32]:
soccer_half_df2 = soccer_half_df.dropna(axis = 0)
soccer_half_df2.isnull().sum()

homeAway                    0
Ball Possession 1st Half    0
Corners 1st Half            0
Fouls Commited 1st Half     0
Goals 1st Half              0
Red Cards 1st Half          0
Shots Off 1st Half          0
Shots On 1st Half           0
Yellow Cards 1st Half       0
Result                      0
dtype: int64

- 결측치 없음 확인

In [33]:
win = (soccer_half_df2['Result'] == 'W')
draw = (soccer_half_df2['Result'] == 'D')
lose = (soccer_half_df2['Result'] == 'L')
soccer_half_df2.loc[win, 'Result'] = 1
soccer_half_df2.loc[draw, 'Result'] = 0
soccer_half_df2.loc[lose, 'Result'] = 0
#또는 soccer_half_df2['Result'] = soccer_half_df2['Result'].map({'W':1, 'D':0, 'L'})

home = (soccer_half_df2['homeAway'] == 1)
soccer_half_df2.loc[home, 'homeAway'] = 0

away = (soccer_half_df2['homeAway'] == 2)
soccer_half_df2.loc[away, 'homeAway'] = 1

In [34]:
#승/비승 여부에 대한 데이터는 타겟 데이터(target data)이므로 target이라는 변수를 따로 생성하여 따로 저장해준다. 
# 승,무,패 데이터는 모델 훈련에 불필요한 데이터 이므로 삭제한다. 

#타겟 데이터 따로 저장
target = soccer_half_df2['Result']
#승, 무, 패 데이터 삭제 -> 이미 대체해서 지울 필요 없음. 

In [52]:
soccer_half_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 530 entries, 0 to 171
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   homeAway                  530 non-null    int64  
 1   Ball Possession 1st Half  530 non-null    float64
 2   Corners 1st Half          530 non-null    float64
 3   Fouls Commited 1st Half   530 non-null    float64
 4   Goals 1st Half            530 non-null    float64
 5   Red Cards 1st Half        530 non-null    float64
 6   Shots Off 1st Half        530 non-null    float64
 7   Shots On 1st Half         530 non-null    float64
 8   Yellow Cards 1st Half     530 non-null    float64
 9   Result                    530 non-null    object 
dtypes: float64(8), int64(1), object(1)
memory usage: 45.5+ KB


In [53]:
#result의 자료형 변경하기
soccer_half_df2['Result'] = soccer_half_df2['Result'].astype(int)

C:\Users\srsr1\AppData\Local\Temp\ipykernel_30524\179968242.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  soccer_half_df2['Result'] = soccer_half_df2['Result'].astype(int)


In [54]:
soccer_half_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 530 entries, 0 to 171
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   homeAway                  530 non-null    int64  
 1   Ball Possession 1st Half  530 non-null    float64
 2   Corners 1st Half          530 non-null    float64
 3   Fouls Commited 1st Half   530 non-null    float64
 4   Goals 1st Half            530 non-null    float64
 5   Red Cards 1st Half        530 non-null    float64
 6   Shots Off 1st Half        530 non-null    float64
 7   Shots On 1st Half         530 non-null    float64
 8   Yellow Cards 1st Half     530 non-null    float64
 9   Result                    530 non-null    int32  
dtypes: float64(8), int32(1), int64(1)
memory usage: 43.5 KB


In [73]:
#input 데이터에 종속변수가 들어가 있어서 종속변수를 제거
soccer_half_df2 = soccer_half_df2.drop(columns=['Result'], axis=1)

In [74]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [122]:
#훈련 데이터와 테스트 데이터 분리
train_input, test_input, train_target, test_target = train_test_split(soccer_half_df2, target, test_size = 0.4, random_state = 0)

In [123]:
print(train_input.shape, test_input.shape, train_target.shape, test_target.shape)

(318, 9) (212, 9) (318,) (212,)


In [124]:
train_target.info()

<class 'pandas.core.series.Series'>
Int64Index: 318 entries, 177 to 130
Series name: Result
Non-Null Count  Dtype 
--------------  ----- 
318 non-null    object
dtypes: object(1)
memory usage: 5.0+ KB


In [125]:
#target 자료형 변경
train_target = train_target.astype(int)
test_target = test_target.astype(int)

In [126]:
train_target.info()

<class 'pandas.core.series.Series'>
Int64Index: 318 entries, 177 to 130
Series name: Result
Non-Null Count  Dtype
--------------  -----
318 non-null    int32
dtypes: int32(1)
memory usage: 3.7 KB


In [127]:
lr_soccer_half = LogisticRegression(max_iter=10000) #max-iter 확인
lr_soccer_half.fit(train_input, train_target)

LogisticRegression(max_iter=10000)

In [128]:
#예측결과 출력
Y_predict = lr_soccer_half.predict(test_input)
print(Y_predict)

[1 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 0
 1 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 0 1 0]


In [129]:
print(soccer_half_df2.head(0))

Empty DataFrame
Columns: [homeAway, Ball Possession 1st Half, Corners 1st Half, Fouls Commited 1st Half, Goals 1st Half, Red Cards 1st Half, Shots Off 1st Half, Shots On 1st Half, Yellow Cards 1st Half]
Index: []


In [130]:
lr_soccer_half.coef_

array([[-0.5165083 ,  0.03423098,  0.17925211,  0.07012245,  1.39070622,
        -0.45924528,  0.1176652 , -0.14811818, -0.5236556 ]])

In [131]:
lr_soccer_half.intercept_

array([-3.50634276])

In [132]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [133]:
confusion_matrix(test_target, Y_predict)

array([[110,  10],
       [ 41,  51]], dtype=int64)

In [134]:
accuracy = accuracy_score(test_target, Y_predict)
precision = precision_score(test_target, Y_predict)
recall = recall_score(test_target, Y_predict)
f1 = f1_score(test_target, Y_predict)

In [135]:
print('정확도: {0:.3f}, 정밀도: {1:.3f}, 재현율: {2:.3f}, F1: {3:.3f}'.format(accuracy, precision, recall, f1))

정확도: 0.759, 정밀도: 0.836, 재현율: 0.554, F1: 0.667


[트러블슈팅]
- 정확도가ㅎ 계속 1이 나온다. 
- data를 잘못 설정한 것 같다. 
- 표준화 전에 타겟 데이터를 target이라는 변수를 따로 생성하여 따로 저장해준다. 
- 다르게 설정해줘야 됐다. 
- 데이터를 나눌 때 자료형도 확인/변경해야 하고 , input 변수에 종속변수인 'Result'를 수동으로 빼주니 결과값이 도출되었다...